-- SQL to add giveaway / raffle rigging fields and columns
-- Generated by prisma migrate diff
-- AlterTable: Add source column to raffle_entries
ALTER TABLE "raffle_entries" ADD COLUMN "source" TEXT NOT NULL DEFAULT 'system';

-- AlterTable: Add columns to raffle_winners
ALTER TABLE "raffle_winners" ADD COLUMN "is_rigged" BOOLEAN DEFAULT false;
ALTER TABLE "raffle_winners" ADD COLUMN "selected_ticket_index" BIGINT;
ALTER TABLE "raffle_winners" ADD COLUMN "spin_number" INTEGER;

-- AlterTable: Add columns to raffles
ALTER TABLE "raffles" ADD COLUMN "number_of_winners" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "raffles" ADD COLUMN "rigging_enabled" BOOLEAN NOT NULL DEFAULT false;

-- Create table: raffle_rigged_winners
CREATE TABLE IF NOT EXISTS "raffle_rigged_winners" (
    "id" BIGSERIAL NOT NULL,
    "raffle_id" BIGINT NOT NULL,
    "entry_id" BIGINT NOT NULL,
    "position" INTEGER NOT NULL,
    CONSTRAINT "raffle_rigged_winners_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "raffle_rigged_winners_raffle_id_position_key" ON "raffle_rigged_winners"("raffle_id", "position");

-- Add foreign keys
ALTER TABLE IF EXISTS "raffle_rigged_winners" ADD CONSTRAINT "raffle_rigged_winners_raffle_id_fkey" FOREIGN KEY ("raffle_id") REFERENCES "raffles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE IF EXISTS "raffle_rigged_winners" ADD CONSTRAINT "raffle_rigged_winners_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "raffle_entries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
