-- SQL to add giveaway / raffle rigging fields and columns
-- Generated by prisma migrate diff
-- AlterTable: Add source column to raffle_entries
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'raffle_entries' AND column_name = 'source'
    ) THEN
        ALTER TABLE "raffle_entries" ADD COLUMN "source" TEXT NOT NULL DEFAULT 'system';
    END IF;
END $$;

-- AlterTable: Add columns to raffle_winners (if table exists)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'raffle_winners') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'raffle_winners' AND column_name = 'is_rigged') THEN
            ALTER TABLE "raffle_winners" ADD COLUMN "is_rigged" BOOLEAN DEFAULT false;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'raffle_winners' AND column_name = 'selected_ticket_index') THEN
            ALTER TABLE "raffle_winners" ADD COLUMN "selected_ticket_index" BIGINT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'raffle_winners' AND column_name = 'spin_number') THEN
            ALTER TABLE "raffle_winners" ADD COLUMN "spin_number" INTEGER;
        END IF;
    END IF;
END $$;

-- AlterTable: Add columns to raffles
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'raffles' AND column_name = 'number_of_winners') THEN
        ALTER TABLE "raffles" ADD COLUMN "number_of_winners" INTEGER NOT NULL DEFAULT 1;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'raffles' AND column_name = 'rigging_enabled') THEN
        ALTER TABLE "raffles" ADD COLUMN "rigging_enabled" BOOLEAN NOT NULL DEFAULT false;
    END IF;
END $$;

-- Create table: raffle_rigged_winners
CREATE TABLE IF NOT EXISTS "raffle_rigged_winners" (
    "id" BIGSERIAL NOT NULL,
    "raffle_id" BIGINT NOT NULL,
    "entry_id" BIGINT NOT NULL,
    "position" INTEGER NOT NULL,
    CONSTRAINT "raffle_rigged_winners_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "raffle_rigged_winners_raffle_id_position_key" ON "raffle_rigged_winners"("raffle_id", "position");

-- Add foreign keys
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'raffle_rigged_winners') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'raffle_rigged_winners_raffle_id_fkey') THEN
            ALTER TABLE "raffle_rigged_winners" ADD CONSTRAINT "raffle_rigged_winners_raffle_id_fkey" FOREIGN KEY ("raffle_id") REFERENCES "raffles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'raffle_rigged_winners_entry_id_fkey') THEN
            ALTER TABLE "raffle_rigged_winners" ADD CONSTRAINT "raffle_rigged_winners_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "raffle_entries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
    END IF;
END $$;
